# MindTouch Î»#
# Copyright (C) 2018 MindTouch, Inc.
# www.mindtouch.com  oss@mindtouch.com
#
# For community documentation and downloads visit mindtouch.com;
# please review the licensing section.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Module: LambdaSharp.Demo
Description: LambdaSharp Demo
Items:

  - Parameter: SlackToken
    Description: Slack verification token
    Scope: SlackCommand
    Default: ""

  - Resource: MessageTable
    Description: DynamoDB table for storing received messages
    Scope: "*"
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH

  - Resource: NotifyRecorderTopic
    Description: The topic for recording messages
    Scope: public
    Type: AWS::SNS::Topic
    Allow: Subscribe

  - Resource: UsagePlan
    Description: Limit usage for REST API
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: DemoUsagePlan
      ApiStages:
        - ApiId: !Ref Module::RestApi
          Stage: !Ref Module::RestApi::Stage
      Description: Sample usage plan for REST API
      Quota:
        Limit: 500
        Period: MONTH

  - Function: RecordMessage
    Description: Record message in a DynamoDB table
    Memory: 128
    Timeout: 30
    Sources:
      - Topic: NotifyRecorderTopic

  - Function: SlackCommand
    Description: Respond to slack commands
    Memory: 128
    Timeout: 30
    Sources:
      - SlackCommand: /slack
